[workspace]
members = ["."]
resolver = "3"

[package]
name = "nbcache"
version = "0.1.0"
edition = "2024"

[features]
default = ["testing"]
zeroize = ["dep:zeroize"]
uuid = ["dep:uuid"]
testing = []

[dependencies]
zeroize = { version = "1.8.2", optional = true }
uuid = { version = "1.23.2", optional = true }
