[workspace]
members = [".", "loom-test"]
resolver = "3"

[package]
name = "nbcache"
version = "0.1.0"
edition = "2024"

[features]
default = ["dev"]
zeroize = ["dep:zeroize"]
uuid = ["dep:uuid"]
loom = ["dep:loom"]
dev = []

[dependencies]
zeroize = { version = "1.8.2", optional = true }
uuid = { version = "1.23.2", optional = true }
loom = { version = "0.7.2", optional = true }
